import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/navbar";

const font = Space_Grotesk({ subsets: ["latin"] });

export const metadata = {
  title: "Quanta",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' className="scroll-smooth">
      <body
        className={`bg-fg min-h-screen  ${font.className}`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
